### ISSUE TITLE
osie-runner should self-update on command

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/osie#32]
Might be unavailable to api in the meantime but its much better than having to wait for the whole fleet to reboot -> deprov -> pre-install.

**Comment by displague** [comment]
Expanding on the context here so we can solution appropriately.  This definitely warrants a proposal, hopefully this text can contribute to that.  Parts of the text I'm adding is paraphrased from @mmlb conversations elsewhere.

@mmlb fact-check me here :-) Some of this may already be in place or may not make any sense.

As an operator and developer, the latest OSIE runner code should be used on running hardware to take advantage of code updates.  Canary builds of OSIE runner should also be permitted.

Active OSIE runners are running the latest OSIE (or a canary) within a certain amount of fuzzy time.

The latest OSIE are currently only realized after hardware has been deprovisioned and enters a preinstall or provisioning state. OSIE bug fixes may be available, but not used. OSIE can be updated manually through deprovisioning, but this could be improved with a scheduler.

Possible Implementation:

A new state, or multiple new states, could be used to indicate that hardware should either reload the OSIE-runner or perform a full reboot (which also benefits from the latest kernel and initrd (modules)).

The API needs to know the OSIE and kernel versions used by given hardware so that the reload or reboot state can be intelligently assigned.

The API must be prepared for available hardware to exit a preinstall state and enter a reload state.

**Comment by jacobweinstock** [comment]
Hey @displague, @mmlb. are states (preinstall or provisioning) Equinix Metal specific states? Also, this is quite stale. Do we want to close this and re-open if/when we maybe get more traction?

**Comment by mmlb** [comment]
Yes very equinix specific and only for legacy provisioning, so nothing tinkerbell related.

**Comment by jacobweinstock** [comment]
Archiving repo, closing issue per [GitHub's recommendation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival).
