### ISSUE TITLE
Cannot build osie in a GitHub Action

### ISSUE THREAD

**Issue by rgl** [tinkerbell/osie#46]
I'm trying to build osie using a GitHub Action Workflow, but its failing due to git-lfs. It seems git-lfs is built by osie, but its failing for some reason.

The command to build osie is in the worflow at https://github.com/rgl/osie/blob/rgl-add-github-actions-workflow/.github/workflows/build.yml#L14

And the error is at https://github.com/rgl/osie/runs/735767628?check_suite_focus=true#step:3:7615.

Can you please help me understand why this is failing?

**Comment by ScottGarman** [comment]
Thanks for reporting this, and apologies for taking so long to respond to it - as a team we're implementing a regular process for reviewing PRs and issues so things like this don't fall through the cracks.

Since this was reported, osie builds have evolved considerably, as has the way we build and install git. You should now be able to run `make help` to view a useful help screen of osie build targets:

```
all              Build the osie container images
deploy           Upload the packaged release to S3
help             Print this help
package          Bundle up all the files needed for an OSIE release
package-common   Bundle up all the architecture independent files
test-aarch64     Run VM based tests for aarch64
test             Run VM based tests
test-x86_64      Run VM based tests for x86_64
```
If you run into new problems trying to run this from a github action, please open a new issue with details.
